# Generated by Django 3.0.8 on 2020-07-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_questions',
            new_name='questions',
        ),
    ]
